-- MySQL Script generated by MySQL Workbench
-- Sun Jun  6 19:07:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `lasy_shop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `lasy_shop` ;


CREATE TABLE IF NOT EXISTS `lasy_shop`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasy_shop`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasy_shop`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NULL,
  `phone` INT(11) NULL,
  `email` VARCHAR(255) NULL,
  `is_deleted` INT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `address` TINYTEXT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role_idx` (`role_id` ASC) ,
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `lasy_shop`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasy_shop`.`user_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasy_shop`.`user_session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `access_token` MEDIUMTEXT NULL,
  `refresh_token` MEDIUMTEXT NULL,
  `expires_in` INT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_session_user1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_user_session_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `lasy_shop`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasy_shop`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasy_shop`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `is_deleted` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasy_shop`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasy_shop`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasy_shop`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasy_shop`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code_product` VARCHAR(255) NULL,
  `title` VARCHAR(255) NULL,
  `web_price` FLOAT NULL,
  `sale` FLOAT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `description` MEDIUMTEXT NULL,
  `is_deleted` INT NULL,
  `type` INT NULL,
  `number_of_likes` INT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category1_idx` (`category_id` ASC) ,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `lasy_shop`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasy_shop`.`banner_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasy_shop`.`banner_image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` MEDIUMTEXT NULL,
  `type` INT NULL,
  `title` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasy_shop`.`image_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasy_shop`.`image_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` MEDIUMTEXT NULL,
  `title` VARCHAR(255) NULL,
  `type` INT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_image_product_product1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_image_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `lasy_shop`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasy_shop`.`color_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasy_shop`.`color_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasy_shop`.`size_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasy_shop`.`size_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasy_shop`.`contact_form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasy_shop`.`contact_form` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(255) NULL,
  `content` MEDIUMTEXT NULL,
  `is_checked` INT NULL,
  `is_deleted` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasy_shop`.`product_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasy_shop`.`product_has_tag` (
  `product_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `tag_id`),
  INDEX `fk_product_has_tag_tag1_idx` (`tag_id` ASC) ,
  INDEX `fk_product_has_tag_product1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_product_has_tag_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `lasy_shop`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `lasy_shop`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasy_shop`.`product_has_color_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasy_shop`.`product_has_color_product` (
  `product_id` INT NOT NULL,
  `color_product_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `color_product_id`),
  INDEX `fk_product_has_color_product_color_product1_idx` (`color_product_id` ASC) ,
  INDEX `fk_product_has_color_product_product1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_product_has_color_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `lasy_shop`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_color_product_color_product1`
    FOREIGN KEY (`color_product_id`)
    REFERENCES `lasy_shop`.`color_product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasy_shop`.`product_has_size_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasy_shop`.`product_has_size_product` (
  `product_id` INT NOT NULL,
  `size_product_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `size_product_id`),
  INDEX `fk_product_has_size_product_size_product1_idx` (`size_product_id` ASC) ,
  INDEX `fk_product_has_size_product_product1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_product_has_size_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `lasy_shop`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_size_product_size_product1`
    FOREIGN KEY (`size_product_id`)
    REFERENCES `lasy_shop`.`size_product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ============ modify db ====================

ALTER TABLE `lasy_shop`.`user` 
ADD COLUMN `password` VARCHAR(100) NULL AFTER `role_id`;


ALTER TABLE `lasy_shop`.`user` 
ADD COLUMN `status` INT NULL DEFAULT 1 AFTER `password`;

ALTER TABLE `lasy_shop`.`product` 
ADD COLUMN `status` INT NULL AFTER `category_id`;

ALTER TABLE `lasy_shop`.`product` 
ADD COLUMN `viewd` INT NULL AFTER `status`;

ALTER TABLE `lasy_shop`.`product` 
CHANGE COLUMN `number_of_likes` `number_of_likes` INT(11) NULL DEFAULT 0 ,
CHANGE COLUMN `viewd` `viewd` INT(11) NULL DEFAULT 0 ;

ALTER TABLE `lasy_shop`.`contact_form` 
CHANGE COLUMN `is_checked` `is_checked` INT(11) NULL DEFAULT 0 ,
CHANGE COLUMN `is_deleted` `is_deleted` INT(11) NULL DEFAULT 0 ;


ALTER TABLE `lasy_shop`.`contact_form` 
ADD COLUMN `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP AFTER `is_deleted`,
ADD COLUMN `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP AFTER `created_at`;


insert into role(id, name) values(1, "Admin");
insert into role(id, name) values(2, "Customer");

insert into user (`id`, `full_name`, `email`, `is_deleted`, `role_id`, `password`, `status`) values (1, 'Admin', 'admin@lasy.com', 0, 1, '$2a$08$2mNpli5yEHiLkbiYLduIo.9O3kaaZ1GwLq91QKk5IbDW2tsuu8aPK', 1);